CueCard/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rest_framework import routers
from cards import views

admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'cards', views.CardViewSet)
router.register(r'authors', views.AuthorViewSet)
router.register(r'sources', views.SourceViewSet)

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'CueCard.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^cards/', include('cards.urls', namespace="cards")),
    url(r'^admin/', include(admin.site.urls)),
)

cards/urls.py
from django.conf.urls import patterns, url

from cards import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^create/$', views.CreateView.as_view(), name='create'),
		url(r'^create/$', views.create, name='create'),
	url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

cards/models.py
import datetime

from django.db import models
from django.utils import timezone

class Author(models.Model):
	first = models.CharField(max_length=256)
	middle = models.CharField(max_length=256)
	last = models.CharField(max_length=256)

	def displayName(self):
		return str(self)

	def __str__(self):
		return self.first + " " + self.middle + " " + self.last

class Source(models.Model):
	author = models.ForeignKey(Author)
	# TODO: Make more general title class
	title = models.CharField(max_length=512)

	def __str__(self):
		return self.title

class Card(models.Model):
	info = models.TextField()
	code = models.CharField(max_length=256)
	citation = models.ForeignKey(Source)
	start_page = models.IntegerField(default=0)
	end_page = models.IntegerField(default=0)
	last_modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		# TODO: A real string concat method
		return self.info[:16] + "..."

class Poll(models.Model):
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date < now
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

	def __str__(self):
		return self.question

class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

cards/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views import generic
from rest_framework import viewsets
from cards.models import Poll, Card, Author, Source
from cards.serializers import CardSerializer, AuthorSerializer, SourceSerializer


def index(request):
	template_name = 'cards/index.html'
	context_object_name = 'card_list'

	latest_cards_list = Card.objects.all().order_by('-last_modified')[:12]
	sources_list = Source.objects.all() # TODO: Pagination
	authors_list = Author.objects.all() # TODO: Pagination
	context = {
		'latest_cards_list': latest_cards_list,
		'sources_list': sources_list,
		'authors_list': authors_list
	}
	return render(request, 'cards/index.html', context)

class CreateView(generic.ListView):
	template_name = 'cards/create.html'
	context_object_name = 'sources_list'

	def get_queryset(self):
		# TODO: Pagination
		return Source.objects.order_by('title')

""" Rest Stuff """
class CardViewSet(viewsets.ModelViewSet):
	"""
	API endpoint that allows cards to be viewed or edited
	"""
	queryset = Card.objects.all()
	serializer_class = CardSerializer

class AuthorViewSet(viewsets.ModelViewSet):
	"""
	API endpoint that allows authors to be viewed or edited
	"""
	queryset = Author.objects.all()
	serializer_class = AuthorSerializer

class SourceViewSet(viewsets.ModelViewSet):
	"""
	API endpoint that allows sources to be viewed or edited
	"""
	queryset = Source.objects.all()
	serializer_class = SourceSerializer

""" Methods """
def create(request):
	return HttpResponseRedirect(reverse('cards:index'))

def vote(request, poll_id):
	p = get_object_or_404(Poll, pk=poll_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the poll voting form.
		return render(request, 'cards/detail.html', {
			'poll': p,
			'error_message': "You didn't select a choice.",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
		return HttpResponseRedirect(reverse('cards:results', args=(p.id,)))

cards/templates/cards/create.html
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<h1>New Card</h1>

{% if error_message %}
<p><strong>
	{{ error_message }}
</strong></p>
{% endif %}

<form role="form" action="{% url 'cards:create' %}" method="post">
{% csrf_token %}
  <div class="form-group">
    <label for="codeInput">Code</label>
    <input type="text" class="form-control" id="codeInput" placeholder="Reference Code">
  </div>
  <div class="form-group">
    <label for="infoInput">Card Info</label>
    <textarea class="form-control" id="infoInput" placeholder="Enter information: a fact, thought or quote">
    </textarea>
  </div>

  <div class="form-group">
  	<label for="citationSelect">Citation</label>
	<select id="citationSelect" class="form-control">
		{% for source in sources_list %}
		<option>
			{{ source.title }}
		</option>
		{% endfor %}
	</select>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

cards/templates/cards/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'cards:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

cards/templates/cards/index.html
{% load staticfiles %}
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'cards/style.css' %}" />

<div class="header-bar">
	<div class="header-items">
		<div id="logo"> </div>
		<button type="button" data-toggle="modal" data-target="#new-card-modal" id="new-card-button" class="btn btn-default">New Card</button>
	</div>
</div>

<!-- New Card Modal -->
<div class="modal fade" id="new-card-modal" tabindex="-1" role="dialog" aria-labelledby="new-card-label" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="new-card-label">New Card</h4>
		</div>
	<div class="modal-body">
		<form role="form" id="new-card-form" action="/api/cards/" method="post">
		{% csrf_token %}
			<div class="form-group">
				<label for="codeInput">Code</label>
				<input type="text" id="codeInput" class="form-control" name="code" placeholder="Reference Code">
			</div>
			<div class="form-group">
				<label for="infoInput">Card Info</label>
				<textarea id="infoInput" class="form-control" name="info" placeholder="Enter information: a fact, thought or quote">
				</textarea>
			</div>
			<div class="form-group container-fluid row">
				<label for="citationSelect">Citation</label>
				<div class="row">
					<div id="citation-selection" class="col-md-6">
						<select id="citationSelect" name="citation" class="form-control">
							{% for source in sources_list %}
							<option value="{{ source.id }}">
								{{ source.title }}
							</option>
							{% endfor %}
						</select>
					</div>
					<div id="new-source-container" class="col-md-6">
						<button type="button" id="new-source-popover" class="btn btn-default" data-container="body" data-toggle="popover" data-placement="top">
	  					New Source
						</button>
					</div>
				</div>
				
			</div>
		  </form>
		  <form role="form" id="new-source-form" action="/api/sources/" method="post">
			{% csrf_token %}
			<div class="form-group">
				<label for="title-input">Title</label>
				<input type="text" id="title-input" class="form-control" name="code" placeholder="Source Title">
			</div>
			<div class="form-group">
				<label for="author-select">Author</label>
				<select id="author-select" name="author" class="form-control">
					{% for author in authors_list %}
					<option value="{{ author.id }}">
						{{ author.displayName }}
					</option>
					{% endfor %}
				</select>
			</div>
			<button type="button" id="new-source-submit" data-toggle="clickover" data-loading-text="Creating Citation..." class="btn btn-success">Done</button>
			</form>
	  </div>
	  <div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		<button type="button" id="new-card-submit" data-loading-text="Creating..." class="btn btn-success">Create</button>
	  </div>
	</div>
  </div>
</div>

{% if latest_cards_list %}
<div class="content">
	<div class="card-list columns">
	{% for card in latest_cards_list %}
		<div class="card">
			<div class="card-header clearfix">
				<div class="tags multi-line-clip">
					{{ card.code }}
				</div>
				<div class="citation multi-line-clip">
					{{ card.citation }}
				</div>
			</div>
			<hr class="red-stripe" />
			<div class="info">
				<p>{{ card.info }}</p>
			</div>
		</div>
	{% endfor %}
	</div>
</div>
{% else %}
	<p>You have no cards!</p>
{% endif %}

<!-- <div class="">
	<div id="new-source-popover-content">
		<form role="form" id="new-source-form" action="/api/sources/" method="post">
			{% csrf_token %}
			<div class="form-group">
				<label for="title-input">Title</label>
				<input type="text" id="title-input" class="form-control" name="code" placeholder="Source Title">
			</div>
			<div class="form-group">
				<label for="author-select">Author</label>
				<select id="author-select" name="author" class="form-control">
					{% for author in authors_list %}
					<option value="{{ author.id }}">
						{{ author.displayName }}
					</option>
					{% endfor %}
				</select>
			</div>
			<button type="button" id="new-source-submit" data-toggle="clickover" data-loading-text="Creating Citation..." class="btn btn-success">Done</button>
		</form>
	</div>
</div> -->

<script src="{% static 'cards/jquery-1.11.1.min.js' %}"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<script src="{% static 'cards/newcard.js' %}"></script>
<script src="{% static 'cards/cards.js' %}"></script>

cards/templates/cards/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'cards:detail' poll.id %}">Vote again?</a>